[package]
name = "poker"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "blackjack/core",
    "blackjack/tui",
]
resolver = "2"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[dependencies]
rand = "0.9.0-alpha.2"
rand_distr = "0.5.0-alpha.3"
